# name: Build
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     types: [opened, synchronize, reopened]
#      paths:
#       - "sonar/**"
# jobs:
#   sonarqube:
#     name: SonarQube
#     runs-on: windows-latest
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
#       - name: SonarQube Scan
#         with: 
#           projectBaseDir: ./sonar
#         uses: SonarSource/sonarqube-scan-action@v5
#         env:
          
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}



# name: Build
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     types: [opened, synchronize, reopened]
#     paths:
#       - "sonar/**"
# jobs:
#   sonarqube:
#     name: SonarQube
#     runs-on: windows-latest
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
#       - name: SonarQube Scan
#         uses: SonarSource/sonarqube-scan-action@v5
#         with:
#           projectBaseDir: ./sonar # Assuming your sonar-project.properties is in the ./sonar directory
#           projectKey:  pavithrachandran70_sonar
#           organization:  pavithrachandran70
#           sonarQubeVersion: latest
#           scannerMode: CLI
#           configMode: projectKey
#           cliVersion: latest
#         env:
#           GIT_TOKEN:${{secrets.GIT_TOKEN}}
#           SONAR_TOKEN:${{ secrets.SONAR_TOKEN }}


name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "sonar/"

jobs:
  sonarqube:
    name: SonarQube
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # For better analysis

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          projectBaseDir: ./sonar
          args: >-
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ env.SONAR_ORGANIZATION }}
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.projectVersion=1.0
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.sources=./src
            -Dsonar.exclusions=/reportWebVitals.ts,/index.tsx
            -Dsonar.tests=./src
            -Dsonar.test.inclusions=/.test.tsx,/.test.ts
            -Dsonar.test.exclusions=/node_modules/,/.spec.ts,/.stories.tsx,/services/,coverage/**
            -Dsonar.language=ts
            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
            
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: pavithrachandran70_sonar
          SONAR_ORGANIZATION:pavithrachandran70




          



